language: python
python:
- '3.5'
- '3.6'
- '3.7'
sudo: false
install:
- pip install ".[test]"
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
deploy:
  provider: pypi
  distributions: sdist
  user: __token__
  password: 
    secure: d8lAVS/lxL3qeq/Vxk+oxXlbEQhk5Iu//jclsgQugoUqjbutjJzt8Lfv4wvXxXzPC3konGghqMDypsft1oJUbqu8EgNoeVSVkNSWncJThPeRe5ZK+RaOcvhGxe7vv2dx/o/LqPgY5x6IqBIsqVnI6FTjWJgtQ2jOThvHD59zwGBP0yJHLu2sfUh/AhhJKjYwp3/qhAB5S3C5dK5kXTb14NiR4wA/lqreZyUymko6wUukD/1WJrJniALqjLNDCJyf7kQZ4eqfiJ8QeCvmHBODqr1SY7CVgCp0rtaJ/ZJgjxp0dpph+HUaauxRTRujSShgy76rtf+jDVqG1mcYHaaJQUYC/n8MrqZhrvFAFJd4g9Lrus76La8mfj8mrWxgcGdcqEgHm1NhVDfSEy83dV7di1rFnq89hD42vz+vBnvxX5aJhh0fwy6lRtuPQhGeW6lMkhphE8VzrNt1y7g7udwT/thO2XjZzBZDuu6+OOum8mukNghSy2j6cnLDQyrLPD/TxmVI+hDw2QWGCXiTXf+LCaVy5uoZbtKrCDnCKB9ZmVMfSUXXcKLGCN2InWQPRqPX4J8/9uMiw/iMquVOGOVZLsr8jRUX26GEn6u9v/kSsfds7pWn0kLfXwwuBc9ZSC3jmfmd2HtuUpQXAGEX5/L20x2FQt4rZYSKYK1DURRA+XU=
  skip_existing: true
